# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Vendas.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6 import QtWidgets
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1104, 593)
        self.actionVenda = QAction(MainWindow)
        self.actionVenda.setObjectName(u"actionVenda")
        self.actionCadastro_Simplificado = QAction(MainWindow)
        self.actionCadastro_Simplificado.setObjectName(u"actionCadastro_Simplificado")
        self.actionConsula_cancela = QAction(MainWindow)
        self.actionConsula_cancela.setObjectName(u"actionConsula_cancela")
        self.actionTroca = QAction(MainWindow)
        self.actionTroca.setObjectName(u"actionTroca")
        self.actionConsulta_Digito = QAction(MainWindow)
        self.actionConsulta_Digito.setObjectName(u"actionConsulta_Digito")
        self.actionConsulta_Produtos = QAction(MainWindow)
        self.actionConsulta_Produtos.setObjectName(u"actionConsulta_Produtos")
        self.actionNota_Fiscal_Venda_Manual = QAction(MainWindow)
        self.actionNota_Fiscal_Venda_Manual.setObjectName(u"actionNota_Fiscal_Venda_Manual")
        self.actionRelatorio_de_Vendas = QAction(MainWindow)
        self.actionRelatorio_de_Vendas.setObjectName(u"actionRelatorio_de_Vendas")
        self.actionConsulta = QAction(MainWindow)
        self.actionConsulta.setObjectName(u"actionConsulta")
        self.actionConsulta_Preco_troca = QAction(MainWindow)
        self.actionConsulta_Preco_troca.setObjectName(u"actionConsulta_Preco_troca")
        self.actionConsulta_Demonstr_o_Aberta = QAction(MainWindow)
        self.actionConsulta_Demonstr_o_Aberta.setObjectName(u"actionConsulta_Demonstr_o_Aberta")
        self.actionRetorno_Gera_Venda = QAction(MainWindow)
        self.actionRetorno_Gera_Venda.setObjectName(u"actionRetorno_Gera_Venda")
        self.actionConsulta_Pedido_PagSeguro = QAction(MainWindow)
        self.actionConsulta_Pedido_PagSeguro.setObjectName(u"actionConsulta_Pedido_PagSeguro")
        self.actionPedido_PagSeguro = QAction(MainWindow)
        self.actionPedido_PagSeguro.setObjectName(u"actionPedido_PagSeguro")
        self.actionDevolu_o_Manual = QAction(MainWindow)
        self.actionDevolu_o_Manual.setObjectName(u"actionDevolu_o_Manual")
        self.actionConsulta_Devolu_o = QAction(MainWindow)
        self.actionConsulta_Devolu_o.setObjectName(u"actionConsulta_Devolu_o")
        self.actionForma_de_Pagamento = QAction(MainWindow)
        self.actionForma_de_Pagamento.setObjectName(u"actionForma_de_Pagamento")
        self.actionCOnsertos = QAction(MainWindow)
        self.actionCOnsertos.setObjectName(u"actionCOnsertos")
        self.actionMotivos_Devolu_o = QAction(MainWindow)
        self.actionMotivos_Devolu_o.setObjectName(u"actionMotivos_Devolu_o")
        self.actionVendedores = QAction(MainWindow)
        self.actionVendedores.setObjectName(u"actionVendedores")
        self.actionCadastro_Vale_Presente = QAction(MainWindow)
        self.actionCadastro_Vale_Presente.setObjectName(u"actionCadastro_Vale_Presente")
        self.actionUsu_rios = QAction(MainWindow)
        self.actionUsu_rios.setObjectName(u"actionUsu_rios")
        self.actionGrupos = QAction(MainWindow)
        self.actionGrupos.setObjectName(u"actionGrupos")
        self.actionProgramas = QAction(MainWindow)
        self.actionProgramas.setObjectName(u"actionProgramas")
        self.actionProgramas_Grupos = QAction(MainWindow)
        self.actionProgramas_Grupos.setObjectName(u"actionProgramas_Grupos")
        self.actionManuten_o = QAction(MainWindow)
        self.actionManuten_o.setObjectName(u"actionManuten_o")
        self.actionConsulta_2 = QAction(MainWindow)
        self.actionConsulta_2.setObjectName(u"actionConsulta_2")
        self.actionRelatorio = QAction(MainWindow)
        self.actionRelatorio.setObjectName(u"actionRelatorio")
        self.actionRedu_o_Z = QAction(MainWindow)
        self.actionRedu_o_Z.setObjectName(u"actionRedu_o_Z")
        self.actionCadastra_Mapa_Resumo = QAction(MainWindow)
        self.actionCadastra_Mapa_Resumo.setObjectName(u"actionCadastra_Mapa_Resumo")
        self.actionConsulta_Mapa_Resumo = QAction(MainWindow)
        self.actionConsulta_Mapa_Resumo.setObjectName(u"actionConsulta_Mapa_Resumo")
        self.actionSuprimento_Fiscal = QAction(MainWindow)
        self.actionSuprimento_Fiscal.setObjectName(u"actionSuprimento_Fiscal")
        self.actionSangria_Fiscal = QAction(MainWindow)
        self.actionSangria_Fiscal.setObjectName(u"actionSangria_Fiscal")
        self.actionRotinas_Especiais = QAction(MainWindow)
        self.actionRotinas_Especiais.setObjectName(u"actionRotinas_Especiais")
        self.actionReimpress_o_de_Cart_o = QAction(MainWindow)
        self.actionReimpress_o_de_Cart_o.setObjectName(u"actionReimpress_o_de_Cart_o")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1104, 21))
        self.menuVendas = QMenu(self.menubar)
        self.menuVendas.setObjectName(u"menuVendas")
        self.menuTroca = QMenu(self.menubar)
        self.menuTroca.setObjectName(u"menuTroca")
        self.menuDemonstra_o = QMenu(self.menubar)
        self.menuDemonstra_o.setObjectName(u"menuDemonstra_o")
        self.menuDevolucao = QMenu(self.menubar)
        self.menuDevolucao.setObjectName(u"menuDevolucao")
        self.menuApoio = QMenu(self.menubar)
        self.menuApoio.setObjectName(u"menuApoio")
        self.menuTabelas = QMenu(self.menuApoio)
        self.menuTabelas.setObjectName(u"menuTabelas")
        self.menuAcessos = QMenu(self.menuApoio)
        self.menuAcessos.setObjectName(u"menuAcessos")
        self.menuConsertos = QMenu(self.menuApoio)
        self.menuConsertos.setObjectName(u"menuConsertos")
        self.menuImpressora_Fiscal = QMenu(self.menuApoio)
        self.menuImpressora_Fiscal.setObjectName(u"menuImpressora_Fiscal")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuVendas.menuAction())
        self.menubar.addAction(self.menuTroca.menuAction())
        self.menubar.addAction(self.menuDemonstra_o.menuAction())
        self.menubar.addAction(self.menuDevolucao.menuAction())
        self.menubar.addAction(self.menuApoio.menuAction())
        self.menuVendas.addAction(self.actionVenda)
        self.menuVendas.addAction(self.actionCadastro_Simplificado)
        self.menuVendas.addAction(self.actionConsula_cancela)
        self.menuVendas.addAction(self.actionConsulta_Digito)
        self.menuVendas.addAction(self.actionConsulta_Produtos)
        self.menuVendas.addAction(self.actionNota_Fiscal_Venda_Manual)
        self.menuVendas.addAction(self.actionRelatorio_de_Vendas)
        self.menuTroca.addAction(self.actionTroca)
        self.menuTroca.addAction(self.actionConsulta)
        self.menuTroca.addAction(self.actionConsulta_Preco_troca)
        self.menuDemonstra_o.addAction(self.actionConsulta_Demonstr_o_Aberta)
        self.menuDemonstra_o.addAction(self.actionRetorno_Gera_Venda)
        self.menuDemonstra_o.addAction(self.actionConsulta_Pedido_PagSeguro)
        self.menuDemonstra_o.addAction(self.actionPedido_PagSeguro)
        self.menuDevolucao.addAction(self.actionDevolu_o_Manual)
        self.menuDevolucao.addAction(self.actionConsulta_Devolu_o)
        self.menuApoio.addAction(self.menuTabelas.menuAction())
        self.menuApoio.addAction(self.menuAcessos.menuAction())
        self.menuApoio.addAction(self.menuConsertos.menuAction())
        self.menuApoio.addAction(self.menuImpressora_Fiscal.menuAction())
        self.menuApoio.addAction(self.actionRotinas_Especiais)
        self.menuApoio.addAction(self.actionReimpress_o_de_Cart_o)
        self.menuTabelas.addAction(self.actionForma_de_Pagamento)
        self.menuTabelas.addAction(self.actionCOnsertos)
        self.menuTabelas.addAction(self.actionMotivos_Devolu_o)
        self.menuTabelas.addAction(self.actionVendedores)
        self.menuTabelas.addAction(self.actionCadastro_Vale_Presente)
        self.menuAcessos.addAction(self.actionUsu_rios)
        self.menuAcessos.addAction(self.actionGrupos)
        self.menuAcessos.addAction(self.actionProgramas)
        self.menuAcessos.addAction(self.actionProgramas_Grupos)
        self.menuConsertos.addAction(self.actionManuten_o)
        self.menuConsertos.addAction(self.actionConsulta_2)
        self.menuConsertos.addAction(self.actionRelatorio)
        self.menuImpressora_Fiscal.addAction(self.actionRedu_o_Z)
        self.menuImpressora_Fiscal.addAction(self.actionCadastra_Mapa_Resumo)
        self.menuImpressora_Fiscal.addAction(self.actionConsulta_Mapa_Resumo)
        self.menuImpressora_Fiscal.addAction(self.actionSuprimento_Fiscal)
        self.menuImpressora_Fiscal.addAction(self.actionSangria_Fiscal)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionVenda.setText(QCoreApplication.translate("MainWindow", u"Venda", None))
        self.actionCadastro_Simplificado.setText(QCoreApplication.translate("MainWindow", u"Cadastro Simplificado", None))
        self.actionConsula_cancela.setText(QCoreApplication.translate("MainWindow", u"Consulta/cancela", None))
        self.actionTroca.setText(QCoreApplication.translate("MainWindow", u"Troca Manual", None))
        self.actionConsulta_Digito.setText(QCoreApplication.translate("MainWindow", u"Consulta Digito", None))
        self.actionConsulta_Produtos.setText(QCoreApplication.translate("MainWindow", u"Consulta Produtos", None))
        self.actionNota_Fiscal_Venda_Manual.setText(QCoreApplication.translate("MainWindow", u"Nota Fiscal Venda Manual", None))
        self.actionRelatorio_de_Vendas.setText(QCoreApplication.translate("MainWindow", u"Relatorio de Vendas", None))
        self.actionConsulta.setText(QCoreApplication.translate("MainWindow", u"Consulta", None))
        self.actionConsulta_Preco_troca.setText(QCoreApplication.translate("MainWindow", u"Consulta Preco troca", None))
        self.actionConsulta_Demonstr_o_Aberta.setText(QCoreApplication.translate("MainWindow", u"Consulta Demonstr\u00e7\u00e3o Aberta", None))
        self.actionRetorno_Gera_Venda.setText(QCoreApplication.translate("MainWindow", u"Retorno / Gera Venda", None))
        self.actionConsulta_Pedido_PagSeguro.setText(QCoreApplication.translate("MainWindow", u"Consulta Pedido PagSeguro", None))
        self.actionPedido_PagSeguro.setText(QCoreApplication.translate("MainWindow", u"Pedido PagSeguro", None))
        self.actionDevolu_o_Manual.setText(QCoreApplication.translate("MainWindow", u"Devolu\u00e7\u00e3o Manual", None))
        self.actionConsulta_Devolu_o.setText(QCoreApplication.translate("MainWindow", u"Consulta Devolu\u00e7\u00e3o", None))
        self.actionForma_de_Pagamento.setText(QCoreApplication.translate("MainWindow", u"Forma de Pagamento", None))
        self.actionCOnsertos.setText(QCoreApplication.translate("MainWindow", u"Consertos", None))
        self.actionMotivos_Devolu_o.setText(QCoreApplication.translate("MainWindow", u"Motivos Devolu\u00e7\u00e3o", None))
        self.actionVendedores.setText(QCoreApplication.translate("MainWindow", u"Vendedores", None))
        self.actionCadastro_Vale_Presente.setText(QCoreApplication.translate("MainWindow", u"Cadastro Vale Presente", None))
        self.actionUsu_rios.setText(QCoreApplication.translate("MainWindow", u"Usu\u00e1rios", None))
        self.actionGrupos.setText(QCoreApplication.translate("MainWindow", u"Grupos", None))
        self.actionProgramas.setText(QCoreApplication.translate("MainWindow", u"Programas", None))
        self.actionProgramas_Grupos.setText(QCoreApplication.translate("MainWindow", u"Programas/Grupos", None))
        self.actionManuten_o.setText(QCoreApplication.translate("MainWindow", u"Manuten\u00e7\u00e3o", None))
        self.actionConsulta_2.setText(QCoreApplication.translate("MainWindow", u"Consulta", None))
        self.actionRelatorio.setText(QCoreApplication.translate("MainWindow", u"Relatorio", None))
        self.actionRedu_o_Z.setText(QCoreApplication.translate("MainWindow", u"Redu\u00e7\u00e3o Z", None))
        self.actionCadastra_Mapa_Resumo.setText(QCoreApplication.translate("MainWindow", u"Cadastra Mapa Resumo", None))
        self.actionConsulta_Mapa_Resumo.setText(QCoreApplication.translate("MainWindow", u"Consulta Mapa Resumo", None))
        self.actionSuprimento_Fiscal.setText(QCoreApplication.translate("MainWindow", u"Suprimento Fiscal", None))
        self.actionSangria_Fiscal.setText(QCoreApplication.translate("MainWindow", u"Sangria Fiscal", None))
        self.actionRotinas_Especiais.setText(QCoreApplication.translate("MainWindow", u"Rotinas Especiais", None))
        self.actionReimpress_o_de_Cart_o.setText(QCoreApplication.translate("MainWindow", u"Reimpress\u00e3o de Cart\u00e3o", None))
        self.menuVendas.setTitle(QCoreApplication.translate("MainWindow", u"Vendas", None))
        self.menuTroca.setTitle(QCoreApplication.translate("MainWindow", u"Troca", None))
        self.menuDemonstra_o.setTitle(QCoreApplication.translate("MainWindow", u"Demonstra\u00e7\u00e3o", None))
        self.menuDevolucao.setTitle(QCoreApplication.translate("MainWindow", u"Devolucao", None))
        self.menuApoio.setTitle(QCoreApplication.translate("MainWindow", u"Apoio", None))
        self.menuTabelas.setTitle(QCoreApplication.translate("MainWindow", u"Tabelas", None))
        self.menuAcessos.setTitle(QCoreApplication.translate("MainWindow", u"Acessos", None))
        self.menuConsertos.setTitle(QCoreApplication.translate("MainWindow", u"Consertos", None))
        self.menuImpressora_Fiscal.setTitle(QCoreApplication.translate("MainWindow", u"Impressora Fiscal", None))
    # retranslateUi

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec())
